//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class emanetoyuncaklar
    {
        public string tc { get; set; }
        public string adsoyad { get; set; }
        public string yas { get; set; }
        public string telefon { get; set; }
        public string barkodno { get; set; }
        public string oyuncakadi { get; set; }
        public string ureticifirma { get; set; }
        public string oyuncakboyutu { get; set; }
        public string oyuncakyasgrubu { get; set; }
        public int oyuncaksayisi { get; set; }
        public string teslimtarihi { get; set; }
        public string iadetarihi { get; set; }
    
        public virtual sepet sepet { get; set; }
        public virtual uye uye { get; set; }
    }
}
