//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oyuncak
    {
        public string barkodno { get; set; }
        public string oyuncakadi { get; set; }
        public string oyuncakboyutu { get; set; }
        public string oyuncakyasgrubu { get; set; }
        public string ureticifirma { get; set; }
        public string oyuncakturu { get; set; }
        public int stoksayisi { get; set; }
        public string rafno { get; set; }
        public string açıklama { get; set; }
        public string kayıttarihi { get; set; }
    
        public virtual sepet sepet { get; set; }
    }
}
