//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sepet()
        {
            this.emanetoyuncaklar = new HashSet<emanetoyuncaklar>();
        }
    
        public string barkodno { get; set; }
        public string oyuncakadi { get; set; }
        public string ureticifirma { get; set; }
        public string oyuncakboyutu { get; set; }
        public string oyuncakyasgrubu { get; set; }
        public int oyuncaksayisi { get; set; }
        public string teslimtarihi { get; set; }
        public string iadetarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emanetoyuncaklar> emanetoyuncaklar { get; set; }
        public virtual oyuncak oyuncak { get; set; }
    }
}
