//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class uye
    {
        public string tc { get; set; }
        public string adsoyad { get; set; }
        public string yas { get; set; }
        public string cinsiyet { get; set; }
        public string telefon { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public int oyuncaksayisi { get; set; }
    
        public virtual emanetoyuncaklar emanetoyuncaklar { get; set; }
    }
}
